pr:
  - master

name: $(date:yyyyMMdd)$(rev:.rr)

stages:
  - stage: build
    jobs:
      - job: build_client
        steps:
          - script: dotnet build --project BookMark.Client/*.csproj
      - job: build_restapi
        steps:
          - script: dotnet build --project BookMark.RestApi/*.csproj
  - stage: test
    jobs:
      - job: run_tests
        steps:
          - script: dotnet test
  - stage: analyze
    jobs:
      - job: analyze_client
        pool:
          vmImage: ubuntu-18.04
        steps:
          - task: DotnetGlobalToolInstaller@0
            inputs:
              name: "dotnet-sonarscanner"
          - script: |
              dotnet sonarscanner begin /k:"bookmark-client" /o:"bookmark-dev" /d:sonar.host.url="https://sonarcloud.io/" /d:sonar.login=$SONAR_LOGIN
              dotnet build
              dotnet sonarscanner end /d:sonar.login=$SONAR_LOGIN
            env:
              SONAR_LOGIN: $(sonar.login)
      - job: analyze_restapi
        pool:
          vmImage: ubuntu-18.04
        steps:
          - task: DotnetGlobalToolInstaller@0
            inputs:
              name: "dotnet-sonarscanner"
          - script: |
              dotnet sonarscanner begin /k:"bookmark-restapi" /o:"bookmark-dev" /d:sonar.host.url="https://sonarcloud.io/" /d:sonar.login=$SONAR_LOGIN
              dotnet build
              dotnet sonarscanner end /d:sonar.login=$SONAR_LOGIN
            env:
              SONAR_LOGIN: $(sonar.login)
  - stage: pack
    jobs:
      - job: pack_client
        steps:
          - task: Docker@2
            inputs:
              command: login
              containerRegistry: docker
          - script: |
              docker image build --file client.dockerfile --tag tylercadena/bookmark-client BookMark.Client
              docker image push tylercadena/bookmark-client
          - task: Docker@2
            inputs:
              command: logout
              containerRegistry: docker
      - job: pack_restapi
        steps:
          - task: Docker@2
            inputs:
              command: login
              containerRegistry: docker
          - script: |
              docker image build --file restapi.dockerfile --tag tylercadena/bookmark-restapi BookMark.RestApi
              docker image push tylercadena/bookmark-restapi
          - task: Docker@2
            inputs:
              command: logout
              containerRegistry: docker
  - stage: deploy
    jobs:
      - job: deploy_app
        steps:
          - task: DockerCompose@0
            displayName: Run services
            inputs:
              action: Run services
              azureSubscriptionEndpoint: $(azure.subscription)
              containerRegistryType: Container Registry
              dockerComposeFile: docker-compose.yaml
              projectName: $(Build.Repository.Name)
              buildImages: false
              detached: false

trigger:
  - master
