pr:
  - azure-trouble

name: $(date:yyyyMMdd)$(rev:.rr)

stages:
  - stage: build
    jobs:
      - job: run_build
        steps:
          - script: dotnet build
  - stage: test
    jobs:
      - job: run_tests
        steps:
          - script: dotnet test
  - stage: analyze
    jobs:
      - job: run_analysis
        pool:
          vmImage: ubuntu-18.04
        steps:
          - task: DotnetGlobalToolInstaller@0
            inputs:
              name: "dotnet-sonarscanner"
          - script: |
              dotnet sonarscanner begin /k:"bookmark-client" /o:"bookmark-dev" /d:sonar.host.url="https://sonarcloud.io/" /d:sonar.login=$SONAR_LOGIN
              dotnet build
              dotnet sonarscanner end /d:sonar.login=$SONAR_LOGIN
  - stage: pack
    jobs:
      - job: pack_client
        steps:
          - task: Docker@2
            inputs:
              command: login
              containerRegistry: docker
          - script: |
              docker image build --file client.dockerfile --tag tylercadena/bookmark-client .
              docker image push tylercadena/bookmark-client
          - task: Docker@2
            inputs:
              command: logout
              containerRegistry: docker
      - job: pack_restapi
        steps:
          - task: Docker@2
            inputs:
              command: login
              containerRegistry: docker
          - script: |
              docker image build --file restapi.dockerfile --tag tylercadena/bookmark-restapi .
              docker image push tylercadena/bookmark-restapi
          - task: Docker@2
            inputs:
              command: logout
              containerRegistry: docker
  # - stage: deploy
  #   jobs:
  #     - job:
  #       pool:
  #         vmImage: ubuntu-18.04
  #       steps:
  #         - task: DockerCompose@0
  #           displayName: Run services
  #           inputs:
  #             action: Run services
  #             azureSubscriptionEndpoint: $(azure.subscription)
  #             containerRegistryType: Container Registry
  #             dockerComposeFile: docker-compose.yaml
  #             projectName: $(Build.Repository.Name)
  #             buildImages: false
  #             detached: false
  #         - task: AzureRmWebAppDeployment@4
  #           inputs:
  #             ConnectionType: AzureRM
  #             azureSubscription: tylercadena(740adccb-1991-4b18-b49f-d6bdc684c399)
  #             appType: webAppContainer
  #             WebAppName: bookmark
  #             DockerNamespace: tylercadena
  #             DockerRepository: bookmark

trigger:
  - azure-trouble
