version: "3.7"

networks:
  skynet:

services:
  database:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment: 
      ACCEPT_EULA: "y"
      SA_PASSWORD: "Password12345"
    build: .
    ports: 
      - 1433:1433
    networks: 
      - skynet
  restapi:
    depends_on: 
      - database
    image: tylercadena/bookmark-restapi
    build: 
      context: .
      dockerfile: restapi.dockerfile
    ports:
      - 5000:80
    networks:
      - skynet
  # client:
  #   depends_on: 
  #     - database
  #     - restapi
  #   image: tylercadena/bookmark-client
  #   build: 
  #     context: .
  #     dockerfile: client.dockerfile
  #   ports:
  #     - 8000:80
  #   networks:
  #     - skynet
