networks:
  skynet:

services:
  client:
    build: 
      context: BookMark.Client
      dockerfile: client.dockerfile
    image: tylercadena/bookmark-client
    ports:
      - 8000:80
    networks:
      - skynet
  restapi:
    build: 
      context: BookMark.RestApi
      dockerfile: restapi.dockerfile
    image: tylercadena/bookmark-restapi
    ports:
      - 5000:80
    networks:
      - skynet

version: "3.7"
