networks:
  skynet

services: 
  client: 
    build: 
      context: BookMark.Client
      dockerfile: client.dockerfile
    image: tcfirstproj/bookmark
    ports: 
      - 8000:80
    networks: 
      - skynet
  restapi: 
    build: 
      context: BookMark.RestApi
      dockerfile: restapi.dockerfile
    image: tcfirstproj/bookmark
    ports:
      - 5000:80
    networks: 
      - skynet

version: "3.7"
